<?php
/**
 * Zkilleman_Piwik
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Piwik.
 *
 * Zkilleman_Piwik is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Piwik is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Piwik. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Piwik
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-piwik
 */
?>
<?php
    $_baseUrl = $this->getBaseUrl();
    $_siteId  = $this->getSiteId();
?>
<!-- Piwik Tracking Code -->
<script type="text/javascript">
//<![CDATA[
    (function() {
        var pa   = document.createElement('script');
        pa.type  = 'text/javascript';
        pa.defer = true;
        pa.async = true;
        pa.src   = '<?php echo $_baseUrl; ?>piwik.js';
        (document.getElementsByTagName('head')[0] ||
            document.getElementsByTagName('body')[0]).appendChild(pa);
    })();

    var _paq = _paq || [];
    _paq.push(['setSiteId', <?php echo $_siteId; ?>]);
    _paq.push(['setTrackerUrl', '<?php echo $_baseUrl; ?>piwik.php']);
    <?php foreach ($this->getOrders() as $order): ?>
        <?php foreach ($order->getItems() as $item): ?>
            _paq.push([
                'addEcommerceItem',
                '<?php echo $item->getSku(); ?>',
                '<?php echo $item->getName(); ?>',
                false,
                <?php echo $item->getPrice(); ?>,
                <?php echo $item->getQty(); ?>
            ]);
        <?php endforeach; ?>
        _paq.push([
            'trackEcommerceOrder',
            '<?php echo $order->getId(); ?>',
            <?php echo $order->getGrandTotal(); ?>,
            <?php echo $order->getSubTotal(); ?>,
            <?php echo $order->getTax(); ?>,
            <?php echo $order->getShipping(); ?>,
            <?php echo $order->getDiscount(); ?>
        ]);
    <?php endforeach; ?>
    <?php if ($this->trackLinks()): ?>
    _paq.push(['enableLinkTracking']);
    _paq.push(['setLinkTrackingTimer', <?php echo $this->getLinkDelay(); ?>]);
    _paq.push(['setIgnoreClasses', <?php echo $this->getLinkIgnoreJson(); ?>]);
    _paq.push(['setLinkClasses', <?php echo $this->getLinkOutlinkJson(); ?>]);
    _paq.push(['setDownloadClasses', <?php echo $this->getLinkDownloadJson(); ?>]);
    <?php endif; ?>
    _paq.push(['trackPageView']);
//]]>
</script>
<noscript>
    <p><img src="<?php echo $_baseUrl; ?>piwik.php?idsite=<?php echo $_siteId; ?>" style="border:0" alt="" /></p>
</noscript>
<!-- End Piwik Tracking Code -->
